version: "3.7"
services:
  service:
    build:
      context: ./
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
