version: "3.7"
services:
  service:
    build:
      context: ./
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_started
      ipfs:
        condition: service_started

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db_data/:/var/lib/postgresql/data/

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
      # - "4001:4001" # ipfs swarm - expose if needed/wanted
    env_file:
      - .env
    volumes:
      - ./ipfs_data:/data/ipfs
